services:
  api:
    image: qgrid-api:dev
    ports:
      - "44900:44900"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        order: stop-first
    environment:
      TZ: Asia/Seoul
      LR: remote
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 44900
      QGRID_DB_PORT: 5432
      QGRID_DB_NAME: qgrid
      QGRID_WORKERS_PER_TOKEN: 3
      QGRID_DB_HOST: ${QGRID_DB_HOST}
      QGRID_DB_USER: ${QGRID_DB_USER}
      QGRID_DB_PASSWORD: ${QGRID_DB_PASSWORD}
      QGRID_PUBLIC_BASE_URL: ${QGRID_PUBLIC_BASE_URL}
